---
# tasks file for ansible-role-qemu-network
- name: Update apt repositories
  apt:
    update_cache: true

- name: Install QEMU and libvirt dependencies
  apt:
    state: present
    name:
      - qemu-system
      - libvirt-daemon-system
      - python3-libvirt
      - python3-lxml

- name: Create virtual bridge interfaces
  blockinfile:
    insertafter: EOF
    path: /etc/network/interfaces
    block: "{{ lookup('template', 'interfaces.j2') }}"
    marker: ""
  loop: {{ qemu_network_networks }}

- name: Define QEMU network
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'bridge-network.xml.j2') }}"
    autostart: true
  loop: {{ qemu_network_networks }}

- name: Start QEMU network
  community.libvirt.virt:
    name: {{ name }}
    state: running
  loop: {{ qemu_network_networks }}

- name: Define QEMU virtual machines
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'virtual-machine.xml.j2') }}"
    autostart: true
  loop: {{ qemu_network_machines }}

- name: Start QEMU virtual machines
  community.libvirt.virt:
    name: {{ name }}
    state: running
